name: Tests
on: [push, pull_request]

jobs:
    unittests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: 3.12
            - name: Install deps
              run: |
                pip install -U pip
                pip install .[tests]
            - name: Run mock server
              uses: actions/checkout@master
              with:
                repository: ptobiasdiaz/adi_token_srv
              run: |
                pip install .
                auth_service
            - name: Run pytest
              run: |
                pytest --cov=tokensrv --cov-report=term-missing -v