name: Tests integracion
on: [push, pull_request]

jobs:
    unittests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: 3.12
            - name: Install deps
              run: |
                pip install -U pip
                pip install .[tests]
            - name: clone mock server
              uses: actions/checkout@master
              with:
                repository: luideoz/Authentication
                path: adi_auth_srv
            - name: Run mock server
              run: |
                cd adi_auth_srv
                pip install .
                python bootstrap.py
                auth_service &
                cd ..
                pip install .
                token_service &
            - name: Run pytest
              run: |
                pytest -v tests/test_integracion.py